# Generated by Django 6.1.1 on 2026-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('threat_level', models.CharField(default='Unknown', max_length=50)),
                ('attack_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
